<?php
return [
    [
        'survey_answer_id'=>1,
        'survey_answer_question_id'=>2,
        'survey_answer_name'=>'One choice',
        'survey_answer_descr'=>'One desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'One choice corrective',
        'correct'=>1,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>2,
        'survey_answer_question_id'=>2,
        'survey_answer_name'=>'Two choice',
        'survey_answer_descr'=>'Two desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Two choice corrective',
        'correct'=>1,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>3,
        'survey_answer_question_id'=>2,
        'survey_answer_name'=>'Three choice',
        'survey_answer_descr'=>'Three desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Three choice corrective',
        'correct'=>1,
        'corrective_action_date'=>null,
    ],
];
