<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => '',
    'Active' => 'مفعل',
    'Add Book' => '',
    'All' => 'الكل',
    'Are you sure to delete this {item}?' => 'هل انت متاكد من حذف هذا ',
    'Book Listing' => '',
    'CSV' => '',
    'Clear selection' => '',
    'Collapse' => '',
    'Collapse All' => '',
    'Comma Separated Values' => '',
    'Delete' => 'حذف',
    'Disable any popup blockers in your browser to ensure proper download.' => 'تعطيل أي مانع النوافذ المنبثقة في المتصفح الخاص بك لضمان التنزيل',
    'Download Selected' => 'تنزيل المختار',
    'Excel' => 'اكسل',
    'Expand' => '',
    'Expand All' => '',
    'Export' => 'استخراج',
    'Export All Data' => 'استخراج الكل',
    'Export Page Data' => 'استخراج محتوي الصفحة',
    'ExportWorksheet' => '',
    'Failed to update editable data due to an unknown server error' => '',
    'Generated' => '',
    'Generating the export file. Please wait...' => '',
    'Grid Export' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'غير مفعل',
    'Invalid editable index or model form name' => 'الفهرس غير صالح للتحرير أو اسم النموذج',
    'Invalid or bad editable data' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'Library' => '',
    'Microsoft Excel 95+' => '',
    'No data found' => '',
    'No valid editable model found' => '',
    'Ok to proceed?' => 'وافق للاستخراج؟',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF',
    'Page' => 'صفحة',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Reset Grid' => '',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => '',
    'Show all data' => '',
    'Show first page data' => '',
    'Tab Delimited Text' => '',
    'Text' => 'نص',
    'The CSV export file will be generated for download.' => 'سيتم إنشاء ملف تصدير CSV للتنزيل.',
    'The EXCEL export file will be generated for download.' => 'سيتم إنشاء ملف تصدير EXCEL للتنزيل.',
    'The HTML export file will be generated for download.' => 'سيتم إنشاء ملف تصدير HTML للتنزيل.',
    'The JSON export file will be generated for download.' => 'سيتم إنشاء ملف تصدير JSON للتنزيل.',
    'The PDF export file will be generated for download.' => 'سيتم إنشاء ملف تصدير PDF للتنزيل.',
    'The TEXT export file will be generated for download.' => 'سيتم إنشاء ملف تصدير TEXT للتنزيل.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Update' => '',
    'View' => '',
    'Yii2 Grid Export (PDF)' => 'PDF',
    'export' => 'استخراج',
    'grid-export' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'عرض <b>{begin, number}-{end, number}</b> من أصل <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'مجموع <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'item' => 'مُدخل',
    'items' => 'مُدخلات',
    'items-few' => 'مُدخلات',
    'items-many' => 'مُدخل',
];
